version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - export IMAGE="$REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION"
  
  build:
    commands:
      # Server
      - docker build -t $IMAGE .
      - docker push $IMAGE

      # Client
      - cd client
      - npm install
      - npm run build
      - npm test
      - cd ../

      - ./deploy/create-config-files.sh $IMAGE

artifacts:
  discard-paths: yes
  files:
    - deploy/remnisense.template.yml
    - dev.config.json
    - prod.config.json