version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  
  build:
    commands:
      - apiImage="$API_REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - clientImage="$CLIENT_REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - ./deploy/create-config-files.sh $apiImage $clientImage

artifacts:
  discard-paths: yes
  files:
    - deploy/remnisense.template.yml
    - dev.config.json
    - prod.config.json