Parameters:
  ApiImage:
    Type: String
    Description: Location of the docker image to use for the Remnisense API
  
  ClientImage:
    Type: String
    Description: Location of the docker image to use for the Remnisense Client
  
  DomainName:
    Type: String
    Description: Domain name to use for this deployment of Remnisense

  DBName:
    Type: String
    Description: Database name

  DBUser:
    Type: String
    Description: Username to use to connect to the database with

  DBPassword:
    Type: String
    Description: Encrypted password to use to connect to the database with

  ScaleDownOffHours:
    Type: String
    Description: Whether or not to scale down the app's ECS services down at 7pm
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  ScaleDownOffHours:
    !Equals 
      - !Ref ScaleDownOffHours
      - 'true'

Resources:
  DecryptedDBPassword:
    Type: Custom::Secret
    Properties:
      ServiceToken: !Sub 
        - arn:aws:lambda:${AWS::Region}:${MasterAccountId}:function:Secret
        - MasterAccountId: !ImportValue cfn-utilities:MasterAccountId
      Ciphertext: !Ref DBPassword

  Database:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      EngineMode: serverless
      EngineVersion: 5.6.10a
      DatabaseName: !Ref DBName
      DBClusterParameterGroupName: default.aurora5.6
      MasterUsername: !Ref DBUser
      MasterUserPassword: !GetAtt DecryptedDBPassword.Plaintext
      DBSubnetGroupName: !ImportValue cfn-utilities:DBSubnetGroupName
      VpcSecurityGroupIds:
        - !ImportValue cfn-utilities:DatabaseSecurityGroupId
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 1
        SecondsUntilAutoPause: 300

  ApiListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue cfn-utilities:HttpListenerArn
      Priority: 5
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ApiTargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref DomainName
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - /api*

  ClientListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue cfn-utilities:HttpListenerArn
      Priority: 6
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ClientTargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref DomainName

  ApiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      VpcId: !ImportValue cfn-utilities:VpcId
      Protocol: HTTP
      Port: 8080
      HealthCheckPath: /api
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30

  ClientTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      VpcId: !ImportValue cfn-utilities:VpcId
      Protocol: HTTP
      Port: 80
      HealthCheckPath: /healthcheck
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName
  
  ApiService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Split
            - ","
            - !ImportValue cfn-utilities:SubnetIds
          SecurityGroups:
            - !ImportValue cfn-utilities:WebSecurityGroupId
            - !ImportValue cfn-utilities:DatabaseSecurityGroupId
          AssignPublicIp: ENABLED
      LoadBalancers:
        - ContainerName: api
          ContainerPort: 80
          TargetGroupArn: !Ref ApiTargetGroup
      TaskDefinition: !Ref ApiTaskDefinition
      DesiredCount: 1
      DeploymentConfiguration:
        MinimumHealthyPercent: 1
        MaximumPercent: 200

  ClientService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Split
            - ","
            - !ImportValue cfn-utilities:SubnetIds
          SecurityGroups:
            - !ImportValue cfn-utilities:WebSecurityGroupId
            - !ImportValue cfn-utilities:DatabaseSecurityGroupId
          AssignPublicIp: ENABLED
      LoadBalancers:
        - ContainerName: client
          ContainerPort: 80
          TargetGroupArn: !Ref ClientTargetGroup
      TaskDefinition: !Ref ClientTaskDefinition
      DesiredCount: 1
      DeploymentConfiguration:
        MinimumHealthyPercent: 1
        MaximumPercent: 200

  ApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: api
          Essential: true
          Image: !Ref ApiImage
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub ${AWS::StackName}-api
          Environment:
            - Name: PORT
              Value: 80
            - Name: BASE_PATH
              Value: /api
            - Name: DB_HOST
              Value: !GetAtt Database.Endpoint.Address
            - Name: DB_NAME
              Value: !Ref DBName
            - Name: DB_USER
              Value: !Ref DBUser
            - Name: ENCRYPTED_DB_PASSWORD
              Value: !Ref DBPassword

  ClientTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: client
          Essential: true
          Image: !Ref ClientImage
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub ${AWS::StackName}-client

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - !ImportValue cfn-utilities:SecretsKeyDecryptPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ecs-tasks.amazonaws.com

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14

  ApiScaleDownConfiguration:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: ScaleDownOffHours
    Properties:
      MaxCapacity: 1
      MinCapacity: 0
      ScheduledActions:
        # Everyday at 7pm CST
        - ScheduledActionName: Down
          StartTime: '2019-11-14T00:00:00Z'
          EndTime: '2999-01-03T00:00:00Z'
          ScalableTargetAction:
            MaxCapacity: 0
            MinCapacity: 0
          Schedule: cron(0 1 * * ? *)
      ResourceId: !Sub service/${Cluster}/${ApiService.Name}
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService 
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ClientScaleDownConfiguration: 
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: ScaleDownOffHours
    Properties:
      MaxCapacity: 1
      MinCapacity: 0
      ScheduledActions:
        # Everyday at 7pm CST
        - ScheduledActionName: Down
          StartTime: '2019-11-14T00:00:00Z'
          EndTime: '2999-01-03T00:00:00Z'
          ScalableTargetAction:
            MaxCapacity: 0
            MinCapacity: 0
          Schedule: cron(0 1 * * ? *)
      ResourceId: !Sub service/${Cluster}/${ClientService.Name}
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService 
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
